-- DimaGo dict_<TR>_<NA>.db schema
-- Generated from dict_TH_CN.db

CREATE TABLE category (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    language_tag  TEXT,                /* Country Code:user native language on the device */
    lang_translate  TEXT,              /* Country Code: language to learn */
    lang_native   TEXT,                /* Country Code:native language */
    name_native   TEXT NOT NULL,
    name_translate TEXT NOT NULL,
    name_EN       TEXT NOT NULL,
    lesson_id     INTEGER DEFAULT 0,   /* unique Id different from id index */
    user_id       INTEGER DEFAULT 0,
    access        INTEGER DEFAULT 0,   /* access code public vs private */
    difficulty    INTEGER DEFAULT 0,   /* 0-easy, 1-medium, 2-hard */
    date_created  TEXT,
    date_modified TEXT,
    count         INTEGER DEFAULT 0,   /* count of words in this category, can be updated when add/remove word */
    count_down    INTEGER DEFAULT 5,   /* count down counter seconds for challenge mode */
    practice_type INTEGER DEFAULT 0,   /* three types of practices/challenges; 0:word, 1:phrase, 2:photo */
    challenge     INTEGER DEFAULT 0,   /* keep the challenge result(need definition) */
    photo         TEXT,                /* link to thumbnail image */
    is_favorite   INTEGER DEFAULT 0，
    score1   INTEGER DEFAULT 0,
    score2   INTEGER DEFAULT 0,
    score3   INTEGER DEFAULT 0,
    score4   INTEGER DEFAULT 0,
    score5   INTEGER DEFAULT 0,
    score6   INTEGER DEFAULT 0,
    score7   INTEGER DEFAULT 0,
    score8   INTEGER DEFAULT 0
);

CREATE TABLE word (
    id                       INTEGER PRIMARY KEY,
    name_native              TEXT NOT NULL,
    name_translate           TEXT NOT NULL,
    name_EN                  TEXT NOT NULL,
    roman_native             TEXT,
    roman_translate          TEXT,
    audio_translate          BLOB,  /* load on demand, pre-load for frequently used word */
    audio_native             BLOB,
    definition_native        TEXT,
    action_native            TEXT,
    definition_translate     TEXT,
    action_translate         TEXT,
    sample1_native           TEXT,
    sample1_translate        TEXT,
    sample1_translate_roman  TEXT, /* romanized translate sample (e.g. Thai RTGS) */
    sample1_native_audio     BLOB,
    sample1_translate_audio  BLOB,
    category_index           INTEGER,
    photo                    TEXT,  /* link to thumbnail image */
    user_id                  INTEGER DEFAULT 0,
    date_created             TEXT DEFAULT '2026-03-30',
    date_modified            TEXT,
    use_count                INTEGER DEFAULT 0,
    is_favorite              INTEGER DEFAULT 0
);

CREATE INDEX idx_word_category ON word(category_index);
CREATE INDEX idx_word_favorite ON word(is_favorite);

-- -----------------------------------------------------------------------------
-- Supabase / PostgreSQL reference (DimaGo remote DB).
-- dbutil.py --commit-force builds live DDL from this same repo’s SQLite file
-- (PRAGMA table_info on category → lessons, word → words); the block below is
-- documentation / manual migration reference. Do not feed past the marker into sqlite3.
-- -----------------------------------------------------------------------------
-- === DIMAGO_SUPABASE_POSTGRES_DDL ===

-- DimaGo → Supabase (PostgreSQL)
-- Matches SQLite: category → lessons, word → words, dict_photo.db → word_photo_blobs

-- ── Optional accounts (for future auth FKs) ───────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        TEXT UNIQUE,
    display_name TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── One row per dict_*.db file on GitHub ──────────────────────────────
CREATE TABLE IF NOT EXISTS vocabulary_bundles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translate_lang  TEXT NOT NULL,
    native_lang     TEXT NOT NULL,
    source_filename TEXT NOT NULL UNIQUE,
    imported_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN vocabulary_bundles.translate_lang IS 'App code e.g. th';
COMMENT ON COLUMN vocabulary_bundles.native_lang IS 'App code e.g. zh_CN';

-- ── SQLite category → lessons ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lessons (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id          BIGINT NOT NULL REFERENCES vocabulary_bundles (id) ON DELETE CASCADE,
    legacy_category_id BIGINT NOT NULL,
    name_native        TEXT NOT NULL,
    name_translate     TEXT NOT NULL,
    name_en            TEXT NOT NULL DEFAULT '',
    lesson_id          BIGINT NOT NULL DEFAULT 0,
    user_id            BIGINT NOT NULL DEFAULT 0,
    language_tag       TEXT,
    lang_translate     TEXT,
    lang_native        TEXT,
    access             INTEGER NOT NULL DEFAULT 0,
    difficulty         INTEGER NOT NULL DEFAULT 0,
    date_created       TEXT,
    date_modified      TEXT,
    count              INTEGER NOT NULL DEFAULT 0,
    count_down         INTEGER NOT NULL DEFAULT 5,
    practice_type      INTEGER,
    challenge          INTEGER NOT NULL DEFAULT 0,
    photo              TEXT,
    is_favorite        SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (bundle_id, legacy_category_id),
    UNIQUE (bundle_id, name_native)
);

CREATE INDEX IF NOT EXISTS idx_lessons_bundle ON lessons (bundle_id);

-- ── SQLite word → words (lesson_id replaces category_index FK) ─────────
CREATE TABLE IF NOT EXISTS words (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id                BIGINT NOT NULL REFERENCES vocabulary_bundles (id) ON DELETE CASCADE,
    lesson_id                BIGINT REFERENCES lessons (id) ON DELETE SET NULL,
    legacy_word_id           BIGINT,
    name_native              TEXT NOT NULL,
    name_translate           TEXT NOT NULL,
    name_en                  TEXT NOT NULL DEFAULT '',
    roman_native             TEXT,
    roman_translate          TEXT,
    audio_translate          BYTEA,
    audio_native             BYTEA,
    definition_native        TEXT,
    action_native            TEXT,
    definition_translate     TEXT,
    action_translate         TEXT,
    sample1_native           TEXT,
    sample1_translate        TEXT,
    sample1_translate_roman  TEXT,
    sample1_native_audio     BYTEA,
    sample1_translate_audio  BYTEA,
    legacy_category_index    BIGINT,
    photo                    TEXT,
    user_id                  BIGINT NOT NULL DEFAULT 0,
    date_created             TEXT,
    date_modified            TEXT,
    use_count                INTEGER NOT NULL DEFAULT 0,
    is_favorite              SMALLINT NOT NULL DEFAULT 0,
    correct_count            INTEGER NOT NULL DEFAULT 0,
    hint                     TEXT
);

CREATE INDEX IF NOT EXISTS idx_words_lesson ON words (lesson_id);
CREATE INDEX IF NOT EXISTS idx_words_bundle ON words (bundle_id);
CREATE INDEX IF NOT EXISTS idx_words_favorite ON words (is_favorite);
CREATE INDEX IF NOT EXISTS idx_words_legacy ON words (bundle_id, legacy_word_id);

-- ── dict_photo.db.photo_dict ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS word_photo_blobs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_row_id  BIGINT NOT NULL UNIQUE,
    rec_id         BIGINT,
    word           TEXT NOT NULL,
    photo          BYTEA,
    format         TEXT
);

CREATE INDEX IF NOT EXISTS idx_word_photo_blobs_word ON word_photo_blobs (word);

-- ── Row Level Security: public read, no write for anon ──────────────────
ALTER TABLE vocabulary_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE words ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_photo_blobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vocabulary_bundles_select_public" ON vocabulary_bundles;
CREATE POLICY "vocabulary_bundles_select_public"
    ON vocabulary_bundles FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "lessons_select_public" ON lessons;
CREATE POLICY "lessons_select_public"
    ON lessons FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "words_select_public" ON words;
CREATE POLICY "words_select_public"
    ON words FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "word_photo_blobs_select_public" ON word_photo_blobs;
CREATE POLICY "word_photo_blobs_select_public"
    ON word_photo_blobs FOR SELECT TO anon, authenticated USING (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON vocabulary_bundles, lessons, words, word_photo_blobs TO anon, authenticated;

-- Align older deployments (idempotent ADD COLUMN)
ALTER TABLE public.lessons
  ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.words
  ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.words
  ADD COLUMN IF NOT EXISTS correct_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.words
  ADD COLUMN IF NOT EXISTS hint TEXT;
