-- PostgreSQL DDL aligned with DIMAGO SQLite vocabulary schema
-- (lib/database_helper.dart, schema.sql).
--
-- SQLite uses tables `category` and `word`. This script provides:
--   lessons  ← category (+ same columns)
--   users    ← for category.user_id / word.user_id style references
--   assets   ← normalized storage for lesson/word media (BLOB/TEXT payloads)
--
-- INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT … GENERATED BY DEFAULT AS IDENTITY
-- BLOB → BYTEA; TEXT dates kept as TIMESTAMPTZ where ISO-8601 is stored in app

BEGIN;

-- ── users ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        TEXT UNIQUE,
    display_name TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- ── lessons (SQLite: category) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lessons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_native     TEXT        NOT NULL DEFAULT '',
    name_translate  TEXT        NOT NULL DEFAULT '',
    name_en         TEXT        NOT NULL DEFAULT '',

    -- SQLite: "unique Id different from id index"
    lesson_id       BIGINT      NOT NULL DEFAULT 0,

    user_id         BIGINT REFERENCES users (id) ON DELETE SET NULL,
    language_tag    TEXT,
    lang_translate  TEXT,
    lang_native     TEXT,
    access          INTEGER     NOT NULL DEFAULT 0,
    difficulty      INTEGER     NOT NULL DEFAULT 0,
    date_created    TIMESTAMPTZ,
    date_modified   TIMESTAMPTZ,
    count           INTEGER     NOT NULL DEFAULT 0,
    count_down      INTEGER     NOT NULL DEFAULT 5,
    practice_type   INTEGER     NOT NULL DEFAULT 0,
    challenge       INTEGER     NOT NULL DEFAULT 0,
    photo           TEXT,
    is_favorite     SMALLINT    NOT NULL DEFAULT 0,

    CONSTRAINT uq_lessons_name_native UNIQUE (name_native)
);

CREATE INDEX IF NOT EXISTS idx_lessons_user_id ON lessons (user_id);
CREATE INDEX IF NOT EXISTS idx_lessons_lesson_id ON lessons (lesson_id);
CREATE INDEX IF NOT EXISTS idx_lessons_favorite ON lessons (is_favorite);

-- ── assets (normalized media; SQLite blobs lived on word / photo on category) ──
-- entity_type: 'lesson' → entity_id = lessons.id ; 'word' → entity_id = word pk when migrated
CREATE TABLE IF NOT EXISTS assets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type  TEXT        NOT NULL
                     CHECK (entity_type IN ('lesson', 'word')),
    entity_id    BIGINT      NOT NULL,
    slot         TEXT        NOT NULL,
    mime_type    TEXT,
    content      BYTEA,
    text_content TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Typical slots: photo, audio_translate, audio_native, sample{1,2,3}_translate_audio
CREATE INDEX IF NOT EXISTS idx_assets_entity ON assets (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_assets_slot ON assets (entity_type, entity_id, slot);

COMMENT ON TABLE users IS 'Account records; links from lessons.user_id (was SQLite category.user_id).';
COMMENT ON TABLE lessons IS 'Maps SQLite table category (vocabulary categories / “lessons”).';
COMMENT ON TABLE assets IS 'Binary or text media; replaces scattered BLOB/TEXT media columns on SQLite word/category.';

COMMIT;
